import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Shippage",
  description: "Terms governing your use of Shippage.",
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:py-24">
      <Link
        href="/"
        className="text-sm text-muted-foreground transition-colors hover:text-foreground"
      >
        &larr; Back to home
      </Link>

      <h1 className="mt-8 text-3xl font-bold text-foreground">
        Terms of Service
      </h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Last updated: March 21, 2026
      </p>

      <div className="mt-8 space-y-8 text-muted-foreground [&_h2]:mt-8 [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:text-foreground [&_p]:mt-3 [&_ul]:mt-3 [&_ul]:list-disc [&_ul]:pl-6 [&_li]:mt-1">
        <section>
          <h2>License</h2>
          <p>
            Shippage is released under the MIT License. You are free to use,
            modify, and distribute the software for any purpose, including
            commercial use, provided you include the original copyright notice
            and license.
          </p>
        </section>

        <section>
          <h2>Generated Code</h2>
          <p>
            All code generated by the Shippage skill is yours. You own it
            completely. There are no usage restrictions, royalties, or
            attribution requirements on the output. Use it however you want.
          </p>
        </section>

        <section>
          <h2>No Warranty</h2>
          <p>
            Shippage is provided &ldquo;as is&rdquo; without warranty of any
            kind. We make no guarantees about the accuracy, completeness, or
            suitability of generated content, including legal pages. Generated
            legal documents are templates and should be reviewed by a qualified
            attorney for your specific jurisdiction.
          </p>
        </section>

        <section>
          <h2>Website Use</h2>
          <p>
            By using shippage.dev, you agree to use the site lawfully and not to
            engage in any activity that could harm the site, its users, or its
            infrastructure.
          </p>
        </section>

        <section>
          <h2>Limitation of Liability</h2>
          <p>
            In no event shall Shippage contributors be liable for any indirect,
            incidental, special, or consequential damages arising from the use
            of the software or this website.
          </p>
        </section>

        <section>
          <h2>Changes</h2>
          <p>
            We may update these terms from time to time. Changes will be posted
            on this page with an updated date.
          </p>
        </section>

        <section>
          <h2>Contact</h2>
          <p>
            Questions about these terms? Email{" "}
            <a
              href="mailto:jahan@agenticmode.ai"
              className="text-primary hover:underline"
            >
              jahan@agenticmode.ai
            </a>
            .
          </p>
        </section>
      </div>
    </main>
  );
}
